# Generated by Django 6.0.2 on 2026-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticlePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fLength', models.FloatField(help_text='Major axis of ellipse [mm]')),
                ('fWidth', models.FloatField(help_text='Minor axis of ellipse [mm]')),
                ('fSize', models.FloatField(help_text='10-log of sum of content of all pixels [photons]')),
                ('fConc', models.FloatField(help_text='Ratio of sum of two highest pixels over fSize')),
                ('fConc1', models.FloatField(help_text='Ratio of highest pixel over fSize')),
                ('fAsym', models.FloatField(help_text='Distance from highest pixel to center, projected onto major axis [mm]')),
                ('fM3Long', models.FloatField(help_text='3rd root of third moment along major axis [mm]')),
                ('fM3Trans', models.FloatField(help_text='3rd root of third moment along minor axis [mm]')),
                ('fAlpha', models.FloatField(help_text='Angle of major axis with vector to origin [deg]')),
                ('fDist', models.FloatField(help_text='Distance from origin to center of ellipse [mm]')),
                ('prediction_label', models.CharField(max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
